backend:
  name: github
  repo: JesusGerardoAguiar/lograf-blog

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: headerImg, label: HeaderImg, widget: image }
      - { name: date, label: Date, widget: date }
      - { label: Reactions, name: reactions, widget: number }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
